---
#Commentaires
# Requis : variables.yml , fourni les arguments d'import / export
#ansible-playbook migrate_site.yml

- hosts: localhost
  tasks:
    - name: "Charger les variables de migration"
      include_vars: variables.yml
      check_mode: no
    - include: tasks/add_host.yml server={{ source }}
    - include: tasks/add_host.yml server={{ target }}
    - debug: msg="Migration de {{ source.domain }}"
    - pause: prompt="Are you sure to continue ? Press return to continue. Press Ctrl+c and then "a" to abort' "
- hosts: "{{ hostvars.localhost.source.host }}"
  tasks:
    - debug: msg="Connexion au serveur cible {{ ansible_host }}"
    - apt: name=python-mysqldb update_cache=yes state=present
      become: true
    - name: "Activer le mode proxy"
      apache2_module: state=present name=proxy_http
- hosts: "{{ hostvars.localhost.target.host }}"
  tasks:
    - debug: msg="Connexion au serveur cible {{ ansible_host }}"
    - apt: name=python-mysqldb update_cache=yes state=present
      become: true
    - apt: name=sshpass update_cache=yes state=present
      become: true
    - include: tasks/rsync.yml
      vars:
        source:
          pass: "{{ hostvars.localhost.source.pass|default(omit) }}"
          port: "{{ hostvars.localhost.source.port }}"
          user: "{{ hostvars.localhost.source.user }}"
          host: "{{ hostvars.localhost.source.host }}"
          path: "{{ hostvars.localhost.source.path }}/"
        target:
          path: "{{ hostvars.localhost.target.path | default(hostvars.localhost.source.path) }}"
- hosts: "{{ hostvars.localhost.source.host }}"
  tasks:
    - name: "Activer la maintenance sur le site {{ hostvars.localhost.source.domain }}"
      copy: src=templates/maintenance.html dest={{ hostvars.localhost.source.path }}/maintenance.html
    - name: "Creer le htaccess si absent"
      file: path={{ hostvars.localhost.source.path }}/.htaccess state=touch
    - name: "Activation de la maintenance"
      blockinfile:
        dest: "{{ hostvars.localhost.source.path }}/.htaccess"
        block: |
          ErrorDocument 503 "Site en maintenance"
          RewriteEngine on
          RewriteCond %{DOCUMENT_ROOT}/maintenance.html -f
          RewriteRule .* maintenance.html [L,R=503]
        insertbefore: BOF
    - name: "Export de la base mysql  {{ hostvars.localhost.source.database.name }}"
      mysql_db: >
        login_user={{ hostvars.localhost.source.database.user }}
        login_password={{ hostvars.localhost.source.database.pass }}
        login_host={{ hostvars.localhost.source.database.host }}
        name={{ hostvars.localhost.source.database.name }}
        config_file=/dev/null
        state=dump
        target=/tmp/{{ hostvars.localhost.source.database.name }}.sql
      when: hostvars.localhost.source.database is defined
- hosts: "{{ hostvars.localhost.target.host }}"
  tasks:
    - include: tasks/rsync.yml
      vars:
        source:
          pass: "{{ hostvars.localhost.source.pass|default(omit) }}"
          port: "{{ hostvars.localhost.source.port }}"
          user: "{{ hostvars.localhost.source.user }}"
          host: "{{ hostvars.localhost.source.host }}"
          path: "/tmp/{{ hostvars.localhost.source.database.name }}.sql"
        target:
          path: "/tmp/{{ hostvars.localhost.source.database.name }}.sql"
      when: hostvars.localhost.source.database is defined
    - name: "Corriger les DEFINER SQL"
      command: sed -i 's#DEFINER.*DEFINER##g' /tmp/{{ hostvars.localhost.source.database.name }}.sql
      args:
        chdir: "/tmp/"
      when: hostvars.localhost.target.database is defined
    - mysql_db: >
        config_file=""
        login_user={{ hostvars.localhost.target.database.user | default(hostvars.localhost.source.database.user) }}
        login_password={{ hostvars.localhost.target.database.pass }}
        login_host={{ hostvars.localhost.target.database.host | default(hostvars.localhost.source.database.host) }}
        name={{ hostvars.localhost.target.database.name | default(hostvars.localhost.source.database.name) }}
        config_file=/dev/null
        state=import
        single_transaction=yes
        target=/tmp/{{ hostvars.localhost.source.database.name }}.sql
      when: hostvars.localhost.source.database is defined or  hostvars.localhost.target.database is defined
    - name: "Synchroniser les informations manquantes depuis l'import initial"
      include: tasks/rsync.yml
      vars:
        source:
          pass: "{{ hostvars.localhost.source.pass|default(omit) }}"
          port: "{{ hostvars.localhost.source.port }}"
          user: "{{ hostvars.localhost.source.user }}"
          host: "{{ hostvars.localhost.source.host }}"
          path: "{{ hostvars.localhost.source.path }}/"
        target:
          path: "{{ hostvars.localhost.target.path | default(hostvars.localhost.source.path) }}"
    - name: "Corriger tous les appels aux anciens chemin avec le nouveau"
      command: find . -type f -exec sed -i 's#{{ hostvars.localhost.source.path }}/#{{ hostvars.localhost.target.path }}/#g' {} +
      args:
        chdir: "{{ hostvars.localhost.target.path }}/"
      when: hostvars.localhost.target.path is defined
    - name: "Corriger la connexion a la db"
      include: "{{ item }}"
      vars:
        path: "{{ hostvars.localhost.target.path | default(hostvars.localhost.source.path) }}"
        database: "{{ hostvars.localhost.source.database | combine(hostvars.localhost.target.database) }}"
      when: hostvars.localhost.source.database is defined or hostvars.localhost.target.database is defined
      with_first_found:
        - files:
            - tasks/{{ hostvars.localhost.source.cms }}_db.yml
          skip: true
    - name: "Corriger les droits sur le repertoire"
      command: /usr/lib/alternc/fixperms.sh -l {{ hostvars.localhost.target.alternc }}
- hosts: "{{ hostvars.localhost.source.host }}"
  tasks:
    - stat:
        path: /etc/apache2/conf.d
      register: apache2confd
    - stat:
        path: /etc/apache2/conf-enabled
      register: apache2confenabled

    - name: "Activation du mode proxy : conf.d"
      template: src=templates/proxy.j2 dest=/etc/apache2/conf.d/000-proxy-{{ hostvars.localhost.source.domain }}.conf
      when: apache2confd.stat.isdir is defined and apache2confd.stat.isdir
    - name: "Activation du mode proxy : conf-enabled"
      template: src=templates/proxy.j2 dest=/etc/apache2/conf-enabled/000-proxy-{{ hostvars.localhost.source.domain }}.conf
      when: apache2confenabled.stat.isdir is defined and apache2confenabled.stat.isdir

    - name: "Relancer apache"
      service: name=apache2 state=reloaded
      when: ansible_distribution == 'Debian'
    - name: "Relancer apache"
      shell: /etc/init.d/apache2 restart
      when: ansible_distribution == 'Ubuntu'