---
- hosts: localhost
  tasks:
    - name: "Charger les variables de migration"
      include_vars: variables.yml
    - name: Déclarer le serveur cible alternc dans l'inventaire
      add_host: hostname={{ target.host }}
        ansible_ssh_user={{ target.user | default("root") }}
        ansible_ssh_port={{ target.port | default(22) }}
        ansible_ssh_common_args={{ target.key | ternary('',"-o PubkeyAuthentication=no -o StrictHostKeyChecking=no") }}
        ansible_ssh_pass={{ target.pass }}
        ansible_become={{ (target.user == "root") | ternary(false,true) }}
        ansible_become_pass={{ target.pass }}
