---
- hosts: localhost
  tasks:
    - name: "Charger les variables de migration"
      include_vars: variables.yml
      always_run: yes
    - name: "Deconnecter les sessions ssh"
      local_action: >
          shell ssh -O stop {{ target.host }}
          -o ControlPath=/tmp/ansible-ssh-{{ target.user | default("root") }}-{{ target.host }}-{{ target.port | default(22) }}
      run_once: yes
      failed_when: >
        socket_removal|failed
        and "No such file or directory" not in socket_removal.stderr
    - name: Déclarer le serveur cible {{ target.host }} dans l'inventaire
      add_host: hostname={{ target.host }}
        ansible_user={{ target.user | default("root") }}
        ansible_port={{ target.port | default(22) }}
        ansible_ssh_common_args="{% if target.key is defined and target.key %} -i {{ target.key }} {% else %} -o PubkeyAuthentication=no -o StrictHostKeyChecking=no {% endif %}"        ansible_ssh_pass={{ target.pass }}
        ansible_ssh_pass={{ target.pass }}
        ansible_become={{ (target.user == "root") | ternary(false,true) }}
        ansible_become_pass={{ target.pass }}
      always_run: yes
- hosts: "{{ hostvars.localhost.target.host }}"
  tasks:
    - debug: msg="Connexion au serveur cible {{ ansible_host }}"